### ISSUE TITLE
InvalidOperationException vetting Castle Windsor Interception unit tests

### ISSUE THREAD

**Issue by mwpowellhtx** [aliostad/PerfIt#45]
I am running the unit tests as a first measure baseline, and getting some errors. Perhaps along the lines that PerfIt needs to be "installed" up front?

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The requested Performance Counter is not a custom counter, it has to be initialized as ReadOnly.
  Source=System
  StackTrace:
       at System.Diagnostics.PerformanceCounter.InitializeImpl()
       at System.Diagnostics.PerformanceCounter.Initialize()
       at System.Diagnostics.PerformanceCounter.set_RawValue(Int64 value)
       at PerfIt.Handlers.CurrentConcurrentCountHandler.<>c__DisplayClass2.<BuildCounters>b__1() in d:\Source\Spikes\PerfIt\mwpowellhtx-working\src\PerfIt\Handlers\CurrentConcurrentCountHandler.cs:line 38
       at System.Lazy`1.CreateValue()
  InnerException: 
```

**Comment by mwpowellhtx** [comment]
I got past the initial exception: there needs to be a Category created. This can get tricky creating/loading, depending on whether a contextual disposal has occurred, i.e. to properly "dispose of", or remove, the category, as in for a unit test.

**Comment by aliostad** [comment]
As you can see this is in Integration tests... not a unit test

**Comment by mwpowellhtx** [comment]
Fair enough, but I don't see the distinction, except to say that the scope is broader than a unit test. One of the conditions being that a **PerformanceCounterCategory** should exist, and/or be torn down afterward. So the assumption today is that the Category will have existed prior to that?
